version: '3.8'

services:
  gateway:
    image: gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - gateway-network
    restart: unless-stopped

networks:
  gateway-network:
    driver: bridge